# Generated by Django 5.1.5 on 2025-01-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerresponse',
            old_name='reponse_text',
            new_name='response_text',
        ),
    ]
